parameters:
  env(INSTAGRAM_API_BASEURL): 'https://graph.instagram.com'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Hardanders\Instagram\:
    resource: '../Classes/*'

  Hardanders\Instagram\Command\AccessTokenRefresherCommand:
    tags:
      - name: 'console.command'
        command: 'instagram:refresh-accesstoken'
        description: 'Refreshes all long lived accesstokens.'

  Hardanders\Instagram\Command\ImportPostsCommand:
    tags:
      - name: 'console.command'
        command: 'instagram:account:import-posts'
        description: 'Imports the posts for a given instagram account.'

  Hardanders\Instagram\Client\InstagramApiClient:
    arguments:
      $requestFactory: '@Psr\Http\Message\RequestFactoryInterface'
      $apiBaseUrl: '%env(INSTAGRAM_API_BASEURL)%'
